# Memory Allocation
org.gradle.jvmargs=-Xmx4G

# Target Versions
minecraft_version=1.21.1
enabled_platforms=neoforge

# Mod Metadata
archives_base_name=Theatrical
mod_version=1.0.0-alpha.1
maven_group=dev.imabad
release_type=ALPHA

# NeoForge & Architectury Engine Versions
architectury_version=13.0.6
neoforge_version=21.1.235

# Parchment Layered Mappings Setup
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Fabric Fallback Variables (Required by Architectury common project evaluation)
fabric_loader_version=0.16.9
fabric_api_version=0.114.0+1.21.1

# Third-Party Dependencies
artnet4j_version=0.6.3
snakeyaml_version=2.2